// flow-typed signature: f3ecbabcb800ef7ffd96920353f52ee6
// flow-typed version: <<STUB>>/@rust-wasm/prelude_v^0.3.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rust-wasm/prelude'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rust-wasm/prelude' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rust-wasm/prelude/dist/rust-wasm-prelude' {
  declare module.exports: any;
}

declare module '@rust-wasm/prelude/rollup.config' {
  declare module.exports: any;
}

declare module '@rust-wasm/prelude/src/index' {
  declare module.exports: any;
}

declare module '@rust-wasm/prelude/src/prelude/__tests__/wrap.tests' {
  declare module.exports: any;
}

declare module '@rust-wasm/prelude/src/prelude/CString' {
  declare module.exports: any;
}

declare module '@rust-wasm/prelude/src/prelude/index' {
  declare module.exports: any;
}

declare module '@rust-wasm/prelude/src/prelude/wrap' {
  declare module.exports: any;
}

declare module '@rust-wasm/prelude/src/types/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rust-wasm/prelude/dist/rust-wasm-prelude.js' {
  declare module.exports: $Exports<'@rust-wasm/prelude/dist/rust-wasm-prelude'>;
}
declare module '@rust-wasm/prelude/rollup.config.js' {
  declare module.exports: $Exports<'@rust-wasm/prelude/rollup.config'>;
}
declare module '@rust-wasm/prelude/src/index.js' {
  declare module.exports: $Exports<'@rust-wasm/prelude/src/index'>;
}
declare module '@rust-wasm/prelude/src/prelude/__tests__/wrap.tests.js' {
  declare module.exports: $Exports<'@rust-wasm/prelude/src/prelude/__tests__/wrap.tests'>;
}
declare module '@rust-wasm/prelude/src/prelude/CString.js' {
  declare module.exports: $Exports<'@rust-wasm/prelude/src/prelude/CString'>;
}
declare module '@rust-wasm/prelude/src/prelude/index.js' {
  declare module.exports: $Exports<'@rust-wasm/prelude/src/prelude/index'>;
}
declare module '@rust-wasm/prelude/src/prelude/wrap.js' {
  declare module.exports: $Exports<'@rust-wasm/prelude/src/prelude/wrap'>;
}
declare module '@rust-wasm/prelude/src/types/index.js' {
  declare module.exports: $Exports<'@rust-wasm/prelude/src/types/index'>;
}
