[package]
name = "examples-memory"
version = "0.1.0"
authors = ["Jason Nall <jsonnull@gmail.com>"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rust-wasm-utils = { path = "../../crates/utils" }
clippy = { optional = true, version = "=0.0.174" }

[features]
lint = ["clippy"]
