language: rust
sudo: false

cache:
  yarn: true

# Re-enable stable when it becomes available
rust:
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  # Node
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 9
  # Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  # wasm-gc
  - cargo install --git https://github.com/alexcrichton/wasm-gc

script:
  - rustup target add wasm32-unknown-unknown
  - cargo build --target wasm32-unknown-unknown
  - cargo test
  - yarn global add lerna
  - lerna bootstrap
  - lerna run build
  - lerna run lint
  - lerna run flow
  - lerna run test
