// flow-typed signature: c78e2ac65599da54d7b83fc97515858d
// flow-typed version: <<STUB>>/@rust-wasm/utils_v^0.3.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rust-wasm/utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rust-wasm/utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rust-wasm/utils/dist/rust-wasm-utils' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/flow-typed/npm/@rust-wasm/prelude_vx.x.x' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/rollup.config' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/src/__tests__/utils.tests' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/src/index' {
  declare module.exports: any;
}

declare module '@rust-wasm/utils/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rust-wasm/utils/dist/rust-wasm-utils.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/dist/rust-wasm-utils'>;
}
declare module '@rust-wasm/utils/flow-typed/npm/@rust-wasm/prelude_vx.x.x.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/flow-typed/npm/@rust-wasm/prelude_vx.x.x'>;
}
declare module '@rust-wasm/utils/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/flow-typed/npm/cross-env_vx.x.x'>;
}
declare module '@rust-wasm/utils/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@rust-wasm/utils/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@rust-wasm/utils/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@rust-wasm/utils/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/flow-typed/npm/jest_v22.x.x'>;
}
declare module '@rust-wasm/utils/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/flow-typed/npm/rollup_vx.x.x'>;
}
declare module '@rust-wasm/utils/rollup.config.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/rollup.config'>;
}
declare module '@rust-wasm/utils/src/__tests__/utils.tests.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/src/__tests__/utils.tests'>;
}
declare module '@rust-wasm/utils/src/index.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/src/index'>;
}
declare module '@rust-wasm/utils/src/utils.js' {
  declare module.exports: $Exports<'@rust-wasm/utils/src/utils'>;
}
