// flow-typed signature: 602a77eb2d405791ed94d69c40d079ff
// flow-typed version: <<STUB>>/fast-text-encoding_v^1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-text-encoding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-text-encoding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-text-encoding/polyfill' {
  declare module.exports: any;
}

declare module 'fast-text-encoding/text' {
  declare module.exports: any;
}

declare module 'fast-text-encoding/text.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-text-encoding/polyfill.js' {
  declare module.exports: $Exports<'fast-text-encoding/polyfill'>;
}
declare module 'fast-text-encoding/text.js' {
  declare module.exports: $Exports<'fast-text-encoding/text'>;
}
declare module 'fast-text-encoding/text.min.js' {
  declare module.exports: $Exports<'fast-text-encoding/text.min'>;
}
